# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oqOFRKeB94jdNAPyagza_bUCYMiBfPaF
"""

from fastapi import FastAPI, File, UploadFile
from fastapi.middleware.cors import CORSMiddleware
import pandas as pd
import joblib
import io

app = FastAPI()

# CORS – allows your frontend anywhere to call this backend
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Load your trained ML model
model = joblib.load("model.pkl")   # <--- your trained model file

@app.post("/predict")
async def predict(file: UploadFile = File(...)):
    # Read uploaded CSV
    contents = await file.read()
    df = pd.read_csv(io.BytesIO(contents))

    # Predict probabilities
    probabilities = model.predict_proba(df)[:, 1]

    # Convert to 0/1 using threshold
    predictions = (probabilities >= 0.5).astype(int)

    # Return result
    return {
        "probabilities": probabilities.tolist(),
        "predictions": predictions.tolist()
    }